/**
 * Auth Reducer
 */

export const SET_AUTH = "SET_AUTH";
export const GET_AUTH = "GET_AUTH";
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_CART = "SET_CART";
export const FETCH_CART_ITEMS_OF_USER = "FETCH_CART_ITEMS_OF_USER";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const EMPTY_CART = "EMPTY_CART";
export const NO_CART = "NO_CART";
export const SET_HOME_CATEGORIES = "SET_HOME_CATEGORIES";
export const SET_GEOIP_DATA = "SET_GEOIP_DATA";
export const SET_DISPLAY_TYPE = "SET_DISPLAY_TYPE";
export const SET_WISHLIST = "SET_WISHLIST";
export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const OPEN_WISHLIST_MODAL = "OPEN_WISHLIST_MODAL";
export const CLOSE_WISHLIST_MODAL = "CLOSE_WISHLIST_MODAL";
export const REMOVE_ITEM_FROM_WISHLIST = "REMOVE_ITEM_TO_WISHLIST";
export const MOVE_ITEM_FROM_CART_TO_WISHLIST =
  "MOVE_ITEM_FROM_CART_TO_WISHLIST";
export const MOVE_ITEM_FROM_WISHLIST_TO_CART =
  "MOVE_ITEM_FROM_WISHLIST_TO_CART";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const SET_DEFAULT_ADDRESS = "SET_DEFAULT_ADDRESS";
